controller_configuration:
  - group_name: larm
    controller_name: /larm_controller
    joint_list:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
  - group_name: rarm
    controller_name: /rarm_controller
    joint_list:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
  - group_name: head
    controller_name: /head_controller
    joint_list:
      - HEAD_JOINT0
      - HEAD_JOINT1
  - group_name: torso
    controller_name: /torso_controller
    joint_list:
      - CHEST_JOINT0
  - group_name: larm_torso
    controller_name: /larm_torso_controller
    joint_list:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - CHEST_JOINT0
  - group_name: rarm_torso
    controller_name: /rarm_torso_controller
    joint_list:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - CHEST_JOINT0
