Name:           ros-kinetic-rtmros-hironx
Version:        2.1.0
Release:        0%{?dist}
Summary:        ROS rtmros_hironx package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rtmros_hironx/
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-hironx-calibration
Requires:       ros-kinetic-hironx-moveit-config
Requires:       ros-kinetic-hironx-ros-bridge
BuildRequires:  ros-kinetic-catkin

%description
The rtmros_hironx package is an operating interface via ROS and OpenRTM, for
Hiro and NEXTAGE OPEN dual-armed robots from Kawada Industries Inc. NOTE for
Hiro users: Utilizing this opensource controller for Hiro requires installation
both on Controller Box (QNX-based) and Vision PC (Ubuntu Linux), and the steps
for it are not shared publicly in order to avoid any possible inconvenience that
can easily be caused by slight mis-operation during installation. Please contact
TORK for an advice.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Sep 07 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 2.1.0-0
- Autogenerated by Bloom

* Thu Aug 10 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 2.0.0-0
- Autogenerated by Bloom

