Name:           ros-indigo-hironx-ros-bridge
Version:        1.0.31
Release:        0%{?dist}
Summary:        ROS hironx_ros_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hironx_ros_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       gnuplot
Requires:       ros-indigo-hrpsys-ros-bridge
Requires:       ros-indigo-moveit-commander
Requires:       ros-indigo-openni2-launch
Requires:       ros-indigo-pr2-controllers-msgs
Requires:       ros-indigo-rosbash
Requires:       ros-indigo-roslang
Requires:       ros-indigo-roslib
Requires:       ros-indigo-rospy
Requires:       ros-indigo-tf
BuildRequires:  gnuplot
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-hrpsys-ros-bridge
BuildRequires:  ros-indigo-mk
BuildRequires:  ros-indigo-pr2-controllers-msgs
BuildRequires:  ros-indigo-rosbash
BuildRequires:  ros-indigo-rosbuild
BuildRequires:  ros-indigo-roslang
BuildRequires:  ros-indigo-roslib
BuildRequires:  ros-indigo-roslint
BuildRequires:  unzip

%description
ROS-OpenRTM interfacing package for the opensource version of Kawada's
Hiro/NEXTAGE dual-arm robot. NOTE: This package is multi-license -- pay
attention to file header in each file where license is declared. For Creative
Commons nc 4.0 applied, see here.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun May 31 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.31-0
- Autogenerated by Bloom

* Thu Apr 16 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.30-0
- Autogenerated by Bloom

* Mon Apr 06 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.29-0
- Autogenerated by Bloom

* Fri Feb 06 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.28-0
- Autogenerated by Bloom

