Name:           ros-hydro-hironx-ros-bridge
Version:        1.0.20
Release:        0%{?dist}
Summary:        ROS hironx_ros_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hironx_ros_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       gnuplot
Requires:       ros-hydro-actionlib
Requires:       ros-hydro-hrpsys >= 315.1.8
Requires:       ros-hydro-hrpsys-ros-bridge
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-rosbash
Requires:       ros-hydro-roslang
Requires:       ros-hydro-rospy
Requires:       ros-hydro-trajectory-msgs
BuildRequires:  gnuplot
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-hrpsys >= 315.1.8
BuildRequires:  ros-hydro-hrpsys-ros-bridge
BuildRequires:  ros-hydro-mk
BuildRequires:  ros-hydro-rosbash
BuildRequires:  ros-hydro-rosbuild
BuildRequires:  ros-hydro-roslang
BuildRequires:  unzip

%description
ROS-OpenRTM interfacing package for Kawada's Hiro dual-arm robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Jul 31 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.20-0
- Autogenerated by Bloom

* Tue Jul 29 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.19-1
- Autogenerated by Bloom

* Mon Jul 28 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.19-0
- Autogenerated by Bloom

