Name:           ros-indigo-hironx-calibration
Version:        2.1.1
Release:        0%{?dist}
Summary:        ROS hironx_calibration package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hironx_calibration
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-calibration-estimation
Requires:       ros-indigo-calibration-launch
Requires:       ros-indigo-kdl-parser
Requires:       ros-indigo-openni2-launch
Requires:       ros-indigo-orocos-kdl
BuildRequires:  ros-indigo-catkin

%description
Launch and configuration files for calibrating hironx using the generic
calibration_setup_helper package. THIS FILE IS AUTOMATICALLY GENERATED BY:
rosrun calibration_setup_helper calibration_setup_helper.py `rospack find
hironx_moveit_config`/HiroNX.urdf --base-link CHEST_JOINT0_Link --arm-tip-link
RARM_JOINT5_Link --head-tip-link HEAD_JOINT1_Link --arm-
controller=rarm_controller/command --head-controller=head_controller/command
--head-camera-frame camera_rgb_optical_frame --head-camera-joint
head_to_kinect_joint

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Feb 20 2019 TORK <dev@opensource-robotics.tokyo.jp> - 2.1.1-0
- Autogenerated by Bloom

* Thu Sep 07 2017 TORK <dev@opensource-robotics.tokyo.jp> - 2.1.0-0
- Autogenerated by Bloom

* Thu Aug 10 2017 TORK <dev@opensource-robotics.tokyo.jp> - 2.0.0-0
- Autogenerated by Bloom

* Fri Jun 02 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.25-0
- Autogenerated by Bloom

* Tue May 09 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.24-0
- Autogenerated by Bloom

* Mon Apr 03 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.23-0
- Autogenerated by Bloom

* Fri Mar 24 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.22-0
- Autogenerated by Bloom

* Thu Mar 16 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.21-0
- Autogenerated by Bloom

* Thu Feb 09 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.20-0
- Autogenerated by Bloom

* Thu Jan 12 2017 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.19-0
- Autogenerated by Bloom

* Fri Oct 28 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.18-0
- Autogenerated by Bloom

* Thu Oct 13 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.17-0
- Autogenerated by Bloom

* Mon Jul 11 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.16-0
- Autogenerated by Bloom

* Thu Jun 02 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.15-0
- Autogenerated by Bloom

* Thu May 19 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.14-0
- Autogenerated by Bloom

* Mon May 16 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.13-1
- Autogenerated by Bloom

* Mon May 16 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.13-0
- Autogenerated by Bloom

* Thu May 05 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.12-0
- Autogenerated by Bloom

* Thu Feb 18 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.11-0
- Autogenerated by Bloom

* Fri Feb 12 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.10-0
- Autogenerated by Bloom

* Fri Feb 05 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.7-0
- Autogenerated by Bloom

* Wed Feb 03 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.6-0
- Autogenerated by Bloom

* Tue Jan 26 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.5-0
- Autogenerated by Bloom

* Mon Jan 25 2016 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.4-0
- Autogenerated by Bloom

* Wed Dec 16 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.3-0
- Autogenerated by Bloom

* Wed Nov 11 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.2-0
- Autogenerated by Bloom

* Mon Nov 02 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.1-0
- Autogenerated by Bloom

* Wed Oct 21 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.1.0-0
- Autogenerated by Bloom

* Fri Sep 11 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.37-0
- Autogenerated by Bloom

* Mon Aug 24 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.36-0
- Autogenerated by Bloom

* Fri Aug 14 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.35-0
- Autogenerated by Bloom

* Tue Aug 04 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.34-0
- Autogenerated by Bloom

* Thu Jul 30 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.33-0
- Autogenerated by Bloom

* Thu Jul 16 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.32-0
- Autogenerated by Bloom

* Sun May 31 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.31-0
- Autogenerated by Bloom

* Thu Apr 16 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.30-0
- Autogenerated by Bloom

* Mon Apr 06 2015 TORK <dev@opensource-robotics.tokyo.jp> - 1.0.29-0
- Autogenerated by Bloom

* Fri Feb 06 2015 Calibration Setup Helper <kei.okada@gmail.com> - 1.0.28-0
- Autogenerated by Bloom

