Name:           ros-kinetic-hironx-calibration
Version:        2.1.0
Release:        0%{?dist}
Summary:        ROS hironx_calibration package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hironx_calibration
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-calibration-estimation
Requires:       ros-kinetic-calibration-launch
Requires:       ros-kinetic-kdl-parser
Requires:       ros-kinetic-openni2-launch
Requires:       ros-kinetic-orocos-kdl
BuildRequires:  ros-kinetic-catkin

%description
Launch and configuration files for calibrating hironx using the generic
calibration_setup_helper package. THIS FILE IS AUTOMATICALLY GENERATED BY:
rosrun calibration_setup_helper calibration_setup_helper.py `rospack find
hironx_moveit_config`/HiroNX.urdf --base-link CHEST_JOINT0_Link --arm-tip-link
RARM_JOINT5_Link --head-tip-link HEAD_JOINT1_Link --arm-
controller=rarm_controller/command --head-controller=head_controller/command
--head-camera-frame camera_rgb_optical_frame --head-camera-joint
head_to_kinect_joint

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Sep 07 2017 TORK <dev@opensource-robotics.tokyo.jp> - 2.1.0-0
- Autogenerated by Bloom

* Thu Aug 10 2017 TORK <dev@opensource-robotics.tokyo.jp> - 2.0.0-0
- Autogenerated by Bloom

