arm_controller:
  topic: rarm_controller/command
  joint_names:
  - RARM_JOINT0
  - RARM_JOINT1
  - RARM_JOINT2
  - RARM_JOINT3
  - RARM_JOINT4
  - RARM_JOINT5
head_controller:
  topic: head_controller/command
  joint_names:
  - HEAD_JOINT0
  - HEAD_JOINT1
